SELECT * FROM PRODUTO;

UPDATE PRODUTO
SET VL_PRODUTO = 10, DESC_PRODUTO = 'LEITE DE MIMSÓ'
WHERE COD_PRODUTO = 1;

DROP TRIGGER PROMO_CHECK;

/* CRIAR UMA TRIGGER NA TABELA ITEM NOTA FISCAL PARA QUE TODAS VEZ QUE SEJA INSERIDO UM ITEM NA NOTA ATUALIZE O VLOR TOTAL*/

